repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 格岩导航 · dmgroup-Navi
alias_en: dmgroup-Navi
alias_cn: 格岩导航
description: A Navigation Website for BYR
keywords: 格岩导航, dmgroup-Navi, 格岩, BUPT, Navi, Navigation
url: http://navi.dmgroup.site/

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
